players = [
    {
        "name": "Mauro",
        "surname": "Icardi",
        "position": "Striker",
        "age": 30,
        "overall": 90,
        "country": "Argentina",
        "team": "Galatasaray",
    },
    {
        "name": "Fernando",
        "surname": "Muslera",
        "position": "Goalkeeper",
        "age": 37,
        "overall": 85,
        "country": "Uruguay",
        "team": "Galatasaray",
    },
    {
        "name": "Wilfred",
        "surname": "Zaha",
        "position": "Striker",
        "age": 30,
        "overall": 90,
        "country": "Ireland",
        "team": "Galatasaray",
    },
    {
        "name": "Lucas",
        "surname": "Torreira",
        "position": "Midfielder",
        "age": 27,
        "overall": 88,
        "country": "Uruguay",
        "team": "Galatasaray",
    },
    {
        "name": "Sacha",
        "surname": "Boey",
        "position": "Defender",
        "age": 23,
        "overall": 88,
        "country": "France",
        "team": "Galatasaray",
    },
    {
        "name": "Ederson",
        "surname": "Moraes",
        "position": "Goalkeeper",
        "age": 30,
        "overall": 90,
        "country": "Brazil",
        "team": "Manchester City",
    },
    {
        "name": "Jeremy",
        "surname": "Doku",
        "position": "Striker",
        "age": 30,
        "overall": 90,
        "country": "Belgium",
        "team": "Manchester City",
    },
    {
        "name": "Erling",
        "surname": "Haaland",
        "position": "Striker",
        "age": 23,
        "overall": 95,
        "country": "Norway",
        "team": "Manchester City",
    },
    {
        "name": "Kevin",
        "surname": "De Bruyne",
        "position": "Midfielder",
        "age": 30,
        "overall": 95,
        "country": "Belgium",
        "team": "Manchester City",
    },
    {
        "name": "Phil",
        "surname": "Foden",
        "position": "Midfielder",
        "age": 23,
        "overall": 90,
        "country": "England",
        "team": "Manchester City",
    },

    {
        "name": "Manuel",
        "surname": "Neuer",
        "position": "Goalkeeper",
        "age": 37,
        "overall": 95,
        "country": "Germany",
        "team": "Bayern Munich",
    },
    
    {
        "name": "Harry",
        "surname": "Kane",
        "position": "Striker",
        "age": 30,
        "overall": 95,
        "country": "England",
        "team": "Bayern Munich",
    },
    
    {
        "name": "Thomas",
        "surname": "Muller",
        "position": "Midfielder",
        "age": 30,
        "overall": 95,
        "country": "Germany",
        "team": "Bayern Munich",
    },
    
    {
        "name": "Jamal",
        "surname": "Musiala",
        "position": "Midfielder",
        "age": 23,
        "overall": 90,
        "country": "Germany",
        "team": "Bayern Munich",
    },
    
    {
        "name": "Leroy",
        "surname": "Sane",
        "position": "Midfielder",
        "age": 23,
        "overall": 90,
        "country": "Germany",
        "team": "Bayern Munich",
    }
    
    
    
]